---
apiVersion: v1
kind: Secret
metadata:
  name: users
  namespace: {{ .Release.Namespace }}
data:
  users.htpasswd: {{ .Values.htpasswd | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: licensekey
  namespace: {{ .Release.Namespace }}
data:
  license.key: {{ .Values.licenseKey | b64enc }}